name: q-research
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy==1.26.4
  - pandas==2.2.2
  - matplotlib==3.9.0
  - scipy==1.13.1
  - tqdm==4.66.4
  - seaborn==0.13.2
  - scikit-learn==1.8.0
  - pytest==8.2.2
  - pip:
    - qiskit==2.4.1
    - cirq-core==1.6.1
    - pytket==2.18.0
    - pytket-qiskit==0.77.0
